### ISSUE TITLE
Support to define namespace declarations

### ISSUE THREAD

**Issue by christiangalsterer** [logstash-plugins/logstash-filter-xml#16]
Currently namespace are supported only when defined at the root element.
This change is to allow to specify namespace declarations in the filter configuration.

I have a working code already and will update the with test and documentation and will create a PR in the next few days.

**Comment by christiangalsterer** [comment]
Created two PR for master and core-api-v1.

**Comment by wiibaa** [comment]
Done in #17 #18 

@suyograo can you close please
