### ISSUE TITLE
Broken external links to w3schools

### ISSUE THREAD

**Issue by GlenRSmith** [logstash-plugins/logstash-filter-xml#25]
In the documentation of the xpath setting
http://www.w3schools.com/xpath/
and
http://www.w3schools.com/xpath/xpath_functions.asp

are broken

Possibly could be
http://www.w3schools.com/xsl/xpath_intro.asp
and
http://www.w3schools.com/xsl/xsl_functions.asp

**Comment by wiibaa** [comment]
Fixed in https://github.com/logstash-plugins/logstash-filter-xml/commit/ae42259fe84efbcc8a2acb58c6fafd590a61882c

@suyograo can you close please
