### ISSUE TITLE
Force Array is defaulted to True

### ISSUE THREAD

**Issue by gmoskovicz** [logstash-plugins/logstash-filter-xml#27]
- Version: 2.x
- Operating System: Any
- Config File (if you have sensitive info, please remove it): Any
- Sample Data: -
- Steps to Reproduce:

Parse any Xml and by default string fields are going to be added as arrays instead of plain fields. `ForceArray` is set to true. It should be set by default to `false`.

**Comment by gmoskovicz** [comment]
So basically the following:

```
<foo><bar>Content</bar></foo>
```

Was being parsed as:

```
{
  "bar": ["Content"]
}
```

Now we have a setting to disable this, so Content can be a simple string.

**Comment by suyograo** [comment]
Fixed in #28
