### ISSUE TITLE
Force_array is not applied correctly.

### ISSUE THREAD

**Issue by radoondas** [logstash-plugins/logstash-filter-xml#46]
Hi, it seems that force_array is not behaving as it should be.

Environment informations:
Logstash 5.3

When trying to parse XML with filter. Parsing is going well except that single values are in arrays even with option force_array=false.

"By default the filter will force single elements to be arrays. Setting this to false will prevent storing single elements in arrays."

The questions here. Is this behaviour OK?
The values extracting from XML are INSIDE of XML tag. Does this option work here as well?

<af type="tenured" id="1" timestamp="Apr 11 21:31:30 2017" intervalms="0.000">
  <tenured freebytes="429496320" totalbytes="8589934592" percent="4" >
Configuration:

xml { 
store_xml => "false" 
source => "message" 
remove_namespaces => "true" 
force_array => "false" 
xpath => [ 
"af/@timestamp","[@metadata][timestamp]", 
"af/gc/tenured/@freebytes","freeafter_bytes",
"af/gc/timesms/@mark","gc_mark_ms", 
"af/gc/timesms/@sweep","gc_sweep_ms", 
"af/gc/timesms/@total","gc_total_ms" 
] 
remove_field => [ "message" ] 
} 
All parsed field is a single value, but filter will force single elements to be arrays:

{ 
"freeafter_bytes" => [ 
[0] "5915011776" 
], 
"gc_total_ms" => [ 
[0] "1409.834" 
], 
"gc_sweep_ms" => [ 
[0] "78.448" 
], 
"gc_mark_ms" => [ 
[0] "982.531" 
] 
} 

Example XML:

<af type="tenured" id="1" timestamp="Apr 11 21:31:30 2017" intervalms="0.000">
  <minimum requested_bytes="64" />
  <time exclusiveaccessms="0.239" meanexclusiveaccessms="0.239" threads="0" lastthreadtid="0x0000000001852500" />
  <refs soft="48642" weak="75171" phantom="2212" dynamicSoftReferenceThreshold="32" maxSoftReferenceThreshold="32" />
  <tenured freebytes="429496320" totalbytes="8589934592" percent="4" >
    <soa freebytes="0" totalbytes="8160438272" percent="0" />
    <loa freebytes="429496320" totalbytes="429496320" percent="100" />
  </tenured>
  <pending-finalizers finalizable="0" reference="0" classloader="0" />
  <gc type="global" id="1" totalid="1" intervalms="0.000">
    <classunloading classloaders="108" classes="9" timevmquiescems="0.000" timetakenms="56.329" />
    <finalization objectsqueued="51884" />
    <timesms mark="601.339" sweep="31.230" compact="0.000" total="690.021" />
    <tenured freebytes="7997710768" totalbytes="8589934592" percent="93" >
      <soa freebytes="7568214448" totalbytes="8160438272" percent="92" />
      <loa freebytes="429496320" totalbytes="429496320" percent="100" />
    </tenured>
  </gc>
  <tenured freebytes="7997709664" totalbytes="8589934592" percent="93" >
    <soa freebytes="7568213344" totalbytes="8160438272" percent="92" />
    <loa freebytes="429496320" totalbytes="429496320" percent="100" />
  </tenured>
  <refs soft="37899" weak="22593" phantom="1568" dynamicSoftReferenceThreshold="29" maxSoftReferenceThreshold="32" />
  <pending-finalizers finalizable="51884" reference="978" classloader="0" />
  <time totalms="703.876" />
</af>
As a workaround I use "mutate", but could you please tell me about force_array. Does it work as I think
or I'm wrong and I should use mutate filter to convert array into single value?

mutate { 
replace => { 
"freeafter_bytes" => "%{[freeafter_bytes][0]}" 
"gc_mark_ms" => "%{[gc_mark_ms][0]}" 
"gc_sweep_ms" => "%{[gc_sweep_ms][0]}" 
"gc_total_ms" => "%{[gc_total_ms][0]}" 
"[@metadata][timestamp]" => "%{[@metadata][timestamp][0]}" 
} 
} 

{ 
"freeafter_bytes" => "5933611912", 
"gcpolicy" => "optthruput", 
"gc_total_ms" => "1505.908", 
"gc_sweep_ms" => "69.508", 
"gc_mark_ms" => "1095.859" 
}
Thanks!

**Comment by nicknameforever** [comment]
The same for Logstash 5.4

**Comment by msanaulla** [comment]
Issue still persists on Logstash 5.5.0

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
The force_array parameter only comes into play when store_xml is true, this is because the option is directly fed into the simpleXML instance. 

My patch fixes a few remaining todo's in the ruby file, as well as reuses this parameter for when store_xml is false. 

If the xpath query results in an array with a single value and force_array is false, it will use the only array element as the value, instead of the array as a whole.

**Comment by DeanStuff** [comment]
Hello, I'm looking for this feature.  I'm using logstash 6.3.2.

Thanks,
Dean

**Comment by A-Hall** [comment]
+1 on this

**Comment by jsvd** [comment]
fixed by #57
