### ISSUE TITLE
Empty events set for failed xpath

### ISSUE THREAD

**Issue by inammathe** [logstash-plugins/logstash-filter-xml#61]
This bug was introduced in https://github.com/logstash-plugins/logstash-filter-xml/pull/57
The issue it creates is for failed xpath queries e.g.

```
xml {
    source => "xmldata"
    target => "data"
    xpath => [ "//foo/text()","xpath_field" ]
}
```
```xml
<foobar>
    some text
</foobar>
```
Will result in empty `[]` fields being set in elastic.

This is due to the `data` variable being initialized and set outside of the `normalized_nodeset` loop with no condition for empty/nil value setting.
See below - https://github.com/logstash-plugins/logstash-filter-xml/blob/d5157e292b19a1ec0b6b7eff470dd65f7e1d7c5a/lib/logstash/filters/xml.rb#L159-L177

I propose https://github.com/logstash-plugins/logstash-filter-xml/pull/59 to address this issue by simply appending an `unless data.nil? || data.empty? ` condition to the set operation. See - https://github.com/logstash-plugins/logstash-filter-xml/pull/59/files#diff-46633c67f32820575bd30a6a35b252c7R176

**Comment by jsvd** [comment]
fixed by #59
