### ISSUE TITLE
Make the `target` option required when `store_xml` is set to true (the default)

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-filter-xml#9]
The `target` option doesn't have any default and is required when the `store_xml` option is set to true.
We should provide a sane default for this value and make sure the register raise a ConfigurationError if the target isn't set and we are effectively storing the xml.

**Comment by PhaedrusTheGreek** [comment]
+1 - Hit this issue

**Comment by wiibaa** [comment]
Fixed by #26 

@suyograo can you close please
